### ISSUE TITLE
问题和建议可在此留言

### ISSUE THREAD

**Issue by zhes2Hen** [pkulab409/pkudsa.realm#3]
对api接口发现的问题和一些建议可以留言于此或开启新issue

**Comment by hji84453** [comment]
希望能加入rungame函数，提供初始化棋盘和游戏状态轮替，与腾讯平台类似，但直接在本地运行游戏，以方便调试（例如使用debug等工具），这对于复杂代码工程非常重要！

**Comment by panwangyue** [comment]
线上平台上支持哪些第三方库？
能否提供线下的对战版本？

**Comment by zhes2Hen** [comment]
之后@Renko6626 会上传一个非标准的线下对战版本，仅作参考。也可以自己写一个写面向对战平台的网络接口来获取标准对战数据

**Comment by zhes2Hen** [comment]
> 线上平台上支持哪些第三方库？ 能否提供线下的对战版本？

第三方库多半不支持。如果你想使用一些第三方库的话请开启新的issue
