### ISSUE TITLE
希望改进Layout相关类实现

### ISSUE THREAD

**Issue by hji84453** [pkulab409/pkudsa.realm#4]
经过详细地研究代码和测试，发现Layout类的相关实现非常慢，比如deepcopy和搜索棋子操作（包括copy Chess类），极大地阻碍了树搜深度，希望能改进一下Layout的实现，把Layout类的实现变得更迅速

**Comment by zhes2Hen** [comment]
可以提供一下测试数据吗？

**Comment by hji84453** [comment]
100000次试验的数据，总耗时24s
![image](https://github.com/pkulab409/pkudsa.realm/assets/153366702/fd445cab-b1cc-44ed-90af-b85bfbb948d4)
如果限制在0.2s内，简单的minimax搜索深度<=2,搜索意义不大

**Comment by zhes2Hen** [comment]
确实deepcopy很慢

**Comment by zhes2Hen** [comment]
已解决，改进后总速度提升约4倍
